### PR TITLE
Mac OSX release

### PR DESCRIPTION
**Pull request by ideoservo**
Check release

### CODE REVIEW

**Comment by gurkanerol** [comment]
When will the mac version for 2.9 be released?

**Comment by arindam-m** [comment]
@ideoservo, thank you for this.

**Comment by ideoservo** [comment]
@arindam-m the version I built in April was only working with model without textures (a bit useless though).
Did not try since then. 

My report was the following:

Hello, I've build a version for MacOSX here
https://github.com/ideoservo/pyslapi/releases/tag/0.21.1-OSX
It works only with models which do not have textures.

See this thread https://forums.sketchup.com/t/su-error-serialisation-when-using-sutexturewritetofile-on-macos-2021-sdk/146194/2

Error log in Blender:
Python: Traceback (most recent call last):
File "/Users/Admin/Library/Application Support/Blender/2.92/scripts/addons/SketchUp_Importer-OSX/init.py", line 886, in execute
context, **keywords)
File "/Users/Admin/Library/Application Support/Blender/2.92/scripts/addons/SketchUp_Importer-OSX/init.py", line 172, in load
self.write_materials(self.skp_model.materials)
File "/Users/Admin/Library/Application Support/Blender/2.92/scripts/addons/SketchUp_Importer-OSX/init.py", line 343, in write_materials
tex.write(tmp_name)
File "sketchup.pyx", line 330, in sketchup.Texture.write
File "sketchup.pyx", line 62, in sketchup.check_result
RuntimeError: Sketchup library giving unexpected results SU_ERROR_SERIALIZATION

location: :-1

**Comment by celsino** [comment]
hi there, i have kinda the same problem! ! Please help ASAP After spending 3.5k on a macbook m1 pro i have this problem! i have a desktop and a laptop with windows and the add-ons work perfect! but i because i need to be more mobil i decided to buy a mac since the battery last way longer! Can someone help me with this?! i am open to spend a few hundreds dolares  if someone willing to spend a little time with this!  My work flow is sketchup and then blender to render my projects! Thank you so much

**Comment by odil24** [comment]
> hi there, i have kinda the same problem! ! Please help ASAP After spending 3.5k on a macbook m1 pro i have this problem! i have a desktop and a laptop with windows and the add-ons work perfect! but i because i need to be more mobil i decided to buy a mac since the battery last way longer! Can someone help me with this?! i am open to spend a few hundreds dolares if someone willing to spend a little time with this! My work flow is sketchup and then blender to render my projects! Thank you so much

Maybe this would make any differences?
https://github.com/oleprinds/pyslapi

**Comment by celsino** [comment]
Hey Odli24.

i Have seen that and i tried to follow but i couldnt finish! 

Copy LayOutAPI.framework and SketchUpAPI.framework from SDK directory to pyslapi ???
where is pyslapi??

sorry but i dont know!


could you help me with that? are you able to import to blender?
its so annoying because this my workflow! i dont mind to pay you or someone else to make my life easy!

**Comment by celsino** [comment]
i need it to work on blender with metal support. 3.1 or 3.2!  i use sketchup 2022!

**Pull request merged**
